EZP-26834 : Add README and LICENCE
ezsystems/ezplatform-i18n pull request #4
Opened 2017-01-12 15:40 UTC by nicolas-bastien

Jira : https://jira.ez.no/browse/EZP-26834

## Description

Add readme and licence files.

## Test

Visually by reading

2017-01-12 22:49 UTC, bdunogier requested changes
Just a few minor remarks, good job !

2017-01-12 22:49 UTC, bdunogier commented on README.md
> +This is a meta repository which centralize EzPlatform translations to ease synchronization with Crowdin.
I'd say "that centralizes".

2017-01-12 22:49 UTC, bdunogier commented on README.md
> +**Important** : This repository is not suppose to be used on a production project, each translation will be
Typo: "supposed".

2017-01-12 22:49 UTC, bdunogier commented on README.md
> +- enable: document.cookie='ez_in_context_translation=1;path=/;'; location.reload();
Format as code, maybe ?

2017-01-12 22:49 UTC, bdunogier commented on README.md
> +Each locale will be stored in it's own repository in [ezplatform-i18n organisation][ezplatform-i18n-org].
"its"

2017-01-12 22:49 UTC, bdunogier commented on README.md
> +    git subsplit init https://github.com/react-php/react
react-php ? copy-paste, or am I missing something ?

2017-01-12 22:49 UTC, bdunogier commented on README.md
> +    " --heads=master
What about multiple branches ?

2017-01-13 08:36 UTC, nicolas-bastien commented on README.md
> +    " --heads=master
Here we can have a list list that 

    --heads="master 2.0"

I guess we can set that during the next release

2017-01-13 08:44 UTC, nicolas-bastien commented
@bdunogier done

You were right about the react thing so I've just retested all from a new folder to validate the process

Should be good now

2017-01-13 11:37 UTC, bdunogier commented on README.md
> +    " --heads=master
Okay.

2017-01-13 11:39 UTC, bdunogier approved these changes
I'd just like the capitalization details fixed, then you can merge.

2017-01-13 11:39 UTC, bdunogier commented on README.md
> +# EzPlatform I18N
We usually spell it "eZ Platform" (see http://ezplatform.com). Also, it is usually spelled i18n (lowercase).

2017-01-13 11:39 UTC, bdunogier commented on README.md
> +If you want to help us on translating EzPlatform feel free to contribute on [EzPlatform project on Crowdin][crowdin-ezplatform].
Capitalization of "eZ Platform".

2017-01-13 11:39 UTC, bdunogier commented on README.md
> +You can enable [Crowdin in context translation][in-context] by setting a specific cookie on a EzPlatform application.
Capitalization.

2017-01-13 13:39 UTC, nicolas-bastien commented
@bdunogier done and merged

2017-01-13 13:39 UTC, merged